export const productsTypes = {
    SET_CATEGORIES: 'SET_CATEGORIES',
    SET_PUBLISHERS: 'SET_PUBLISHERS',
    SET_AUTHORS: 'SET_AUTHORS',
    SET_BOOKS: 'SET_BOOKS',
    SET_TOTAL_BOOKS_PAGE: 'SET_TOTAL_BOOK_PAGE'
}

export const userTypes = {
    SET_USER: 'SET_USER',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    SET_ADDRESS: 'SET_ADDRESS',
    SET_ADDRESS_TOTAL_PAGE: 'SET_ADDRESS_TOTAL_PAGE',
    SET_USER_TOTAL_PAGE: 'SET_USER_TOTAL_PAGE'
}

export const homeTypes = {
    SET_TOP_PRODUCT:' SET_TOP_PRODUCT',
    SET_BANNERS: 'SET_BANNERS'
}