export const productsTypes = {
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_PUBLISHERS: "SET_PUBLISHERS",
  SET_AUTHORS: "SET_AUTHORS",
  SET_BOOKS: "SET_BOOKS",
  SET_TOTAL_BOOKS_PAGE: "SET_TOTAL_BOOK_PAGE",
};

export const userTypes = {
  SET_USER: "SET_USER",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  SET_ADDRESS: "SET_ADDRESS",
  SET_ADDRESS_TOTAL_PAGE: "SET_ADDRESS_TOTAL_PAGE",
  SET_USER_TOTAL_PAGE: "SET_USER_TOTAL_PAGE",
};

export const homeTypes = {
  SET_TOP_PRODUCT: " SET_TOP_PRODUCT",
  SET_BANNERS: "SET_BANNERS",
  SET_REVENUE: "SET_REVENUE",
  SET_TOTAL_REVENUE: "SET_TOTAL_REVENUE",
};

export const billTypes = {
  SET_BILL: " SET_BILL",
  SET_BILL_TOTAL_PAGE: "SET_BILL_TOTAL_PAGE",
};
