export const productsTypes = {
    SET_CATEGORIES: 'SET_CATEGORIES',
    SET_PUBLISHERS: 'SET_PUBLISHERS',
    SET_AUTHORS: 'SET_CATEGORIES',
    SET_BOOKS: 'SET_BOOKS',
    SET_TOTAL_BOOKS_PAGE: 'SET_TOTAL_BOOK_PAGE'
}

export const userTypes = {
    SET_USER: 'SET_USER',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_FAIL: 'ADD_USER_FAIL',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',
    RESET_USER: 'RESET_USER',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    SET_PAGE: 'SET_PAGE',
    SET_TOTAL_PAGE:'SET_TOTAL_PAGE'
}

export const homeTypes = {
    SET_TOP_PRODUCT:' SET_TOP_PRODUCT',
    SET_BANNERS: 'SET_BANNERS'
}